name: Produce Release
on:
  push:
    tags:
      - '*'


permissions:
  contents: write
  id-token: write

jobs:
  build-linux-x64:
    name: Build for Linux (AMD64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq build-essential cmake clang qtbase5-dev
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        run: |
          export CC=clang export CXX=clang++
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Run Tests
        run: |
          ./build/bin/tests

      - name: Produce Artifact
        run: |
          mkdir -p artifact/lib
          cp build/lib/libhexplore.so* artifact/lib/          
          cp -R include artifact/
          rm artifact/include/libhexplore/CMakeLists.txt
          cd artifact && zip -q -m -r ../libhexplore-${{env.tag}}.zip ./* && cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: upload-linux-artifact
        with: 
          name: libhexplore-linux
          path: libhexplore-${{env.tag}}-amd64.zip
          if-no-files-found: error
          retention-days: 1

  build-linux-arm64:
    name: Build for Linux (ARM64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq build-essential cmake clang binutils-aarch64-linux-gnu \
          libc6-dev-arm64-cross g++-aarch64-linux-gnu qtbase5-dev
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        run: |
          export TARGET=aarch64-linux-gnu
          export SYSROOT=/usr/$TARGET
          export CC="clang --target=$TARGET --sysroot=$SYSROOT"
          export CXX="clang++ --target=$TARGET --sysroot=$SYSROOT"
          export LD=$TARGET-ld
          export AS=$TARGET-as
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DCMAKE_C_COMPILER=$CC -DCMAKE_FIND_ROOT_PATH=$SYSROOT 
          cmake --build build --config Release

      - name: Run Tests
        run: |
          ./build/bin/tests

      - name: Produce Artifact
        run: |
          mkdir -p artifact/lib
          cp build/lib/libhexplore.so* artifact/lib/          
          cp -R include artifact/
          rm artifact/include/libhexplore/CMakeLists.txt
          cd artifact && zip -q -m -r ../libhexplore-${{env.tag}}.zip ./* && cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: upload-linux-artifact
        with: 
          name: libhexplore-linux
          path: libhexplore-${{env.tag}}-arm64.zip
          if-no-files-found: error
          retention-days: 1

  publish-release:
    needs: 
      - build-linux-x64
      - build-linux-arm64
    runs-on: ubuntu-latest
    steps: 

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Release 
        uses: ncipollo/release-action@v1
        with:
          artifacts: libhexplore-${{env.tag}}-amd64.zip libhexplore-${{env.tag}}-arm64.zip
          omitBody: true
          prerelease: true
     
    




      
